- name: Deploy Patroni configuration file
  ansible.builtin.template:
    src: patroni_template.yml.j2
    dest: /etc/patroni/config.yml
    owner: postgres
    group: postgres
    mode: "0644"
  notify:
    - Restart Patroni service
